# Step 1: Form Pairs

## Developer Role: Razan

## Gatekeeper Role: Ghala


# Step 2: Developer Role# Lab | Numpy Deep Dive

In [1]:
### [your code here]
import numpy as np


In [10]:
### [your code here]
print("NumPy Version:", np.__version__)
np.show_config()


NumPy Version: 1.23.5
blas_armpl_info:
  NOT AVAILABLE
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Admin/anaconda4\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Admin/anaconda4\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Admin/anaconda4\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Admin/anaconda4\\Library\\include']
lapack_armpl_info:
  NOT AVAILABLE
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Admin/anaconda4\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Admin/anaconda4\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Admin/anaconda4\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/User

In [6]:
### [your code here]
a=np.random.randint(10, size=(2,3,5))


In [32]:
### [your code here]
print(a)
a.shape


[[[5 0 5 3 4]
  [7 2 8 0 7]
  [6 0 4 5 3]]

 [[9 5 4 0 9]
  [0 2 6 3 2]
  [5 3 5 2 0]]]


(2, 3, 5)

In [8]:
### [your code here]
b=np.ones((5,2,3))


In [31]:
### [your code here]
print(b)
b.shape


[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


(5, 2, 3)

In [16]:
### [your code here]
print(a.shape)
print(b.shape)
# no matrix a and b does not have the same size 
same_size = a.shape == b.shape
print(same_size)



(2, 3, 5)
(5, 2, 3)
False


In [ ]:
### [your code here]
can_add=a.shape==b.shape
print(can_add)
# no i am not able to add a and b because they have different sizes and it should be the same size of column in first matrix with the first row in the second matrix



False


In [39]:
### [your code here]
c = b.transpose(1,2,0)
print(c)
c.shape


[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


(2, 3, 5)

In [36]:
### [your code here]
d=a+c


In [ ]:
### [your code here]
print(a)
print(d)
#



[[[5 0 5 3 4]
  [7 2 8 0 7]
  [6 0 4 5 3]]

 [[9 5 4 0 9]
  [0 2 6 3 2]
  [5 3 5 2 0]]]
[[[ 6.  1.  6.  4.  5.]
  [ 8.  3.  9.  1.  8.]
  [ 7.  1.  5.  6.  4.]]

 [[10.  6.  5.  1. 10.]
  [ 1.  3.  7.  4.  3.]
  [ 6.  4.  6.  3.  1.]]]


In [42]:
### [your code here]
e=a*c
print(e)
e.shape


[[[5. 0. 5. 3. 4.]
  [7. 2. 8. 0. 7.]
  [6. 0. 4. 5. 3.]]

 [[9. 5. 4. 0. 9.]
  [0. 2. 6. 3. 2.]
  [5. 3. 5. 2. 0.]]]


(2, 3, 5)

In [ ]:
### [your code here]
eq=a.shape==e.shape
print(eq)
print(e.shape)
print(a.shape)
# yes e equals to a they both have the same shape and size



True
(2, 3, 5)
(2, 3, 5)


In [47]:
### [your code here]
d_max=np.max(d)
d_min=np.min(d)
d_mean=np.mean(d)



In [48]:
### [your code here]
f=np.empty((2,3,5))


In [75]:
### [your code here]
f = np.empty(d.shape)

for i in range(d.shape[0]):  
    for j in range(d.shape[1]):  
        for k in range(d.shape[2]):  
            if d_min < d[i, j, k] < d_mean:
                f[i, j, k] = 25
            elif d_mean < d[i, j, k] < d_max:
                f[i, j, k] = 75
            elif d[i,j,k]== d_max:
                f[i, j, k] = 100
            else:
                  f[i, j, k] = 0  








In [76]:
### [your code here]
print(d)
print(f)


[[[ 6.  1.  6.  4.  5.]
  [ 8.  3.  9.  1.  8.]
  [ 7.  1.  5.  6.  4.]]

 [[10.  6.  5.  1. 10.]
  [ 1.  3.  7.  4.  3.]
  [ 6.  4.  6.  3.  1.]]]
[[[ 75.   0.  75.  25.  75.]
  [ 75.  25.  75.   0.  75.]
  [ 75.   0.  75.  75.  25.]]

 [[100.  75.  75.   0. 100.]
  [  0.  25.  75.  25.  25.]
  [ 75.  25.  75.  25.   0.]]]


# Step 3: Gatekeeper Role

In [1]:
print("Hello world")

Hello world
