# Lab | Numpy Deep Dive

### 1. Import the NUMPY package under the name np.


In [1]:
### [your code here]
import numpy as np




### 2. Print the NUMPY version and the configuration.


In [10]:
### [your code here]
print("NumPy Version:", np.__version__)
np.show_config()


NumPy Version: 1.23.5
blas_armpl_info:
  NOT AVAILABLE
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Admin/anaconda4\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Admin/anaconda4\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Admin/anaconda4\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Admin/anaconda4\\Library\\include']
lapack_armpl_info:
  NOT AVAILABLE
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Admin/anaconda4\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Admin/anaconda4\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Admin/anaconda4\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/User

### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?


In [6]:
### [your code here]
a=np.random.randint(10, size=(2,3,5))



### 4. Print a.


In [32]:
### [your code here]
print(a)
a.shape


[[[5 0 5 3 4]
  [7 2 8 0 7]
  [6 0 4 5 3]]

 [[9 5 4 0 9]
  [0 2 6 3 2]
  [5 3 5 2 0]]]


(2, 3, 5)

### 5. Create a 5x2x3 3-dimensional array with all values equaling 1.
### Assign the array to variable "b"


In [8]:
### [your code here]
b=np.ones((5,2,3))



### 6. Print b.


In [31]:
### [your code here]
print(b)
b.shape


[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


(5, 2, 3)


### 7. Do a and b have the same size? How do you prove that in Python code?


In [16]:
### [your code here]
print(a.shape)
print(b.shape)
# no matrix a and b does not have the same size 
same_size = a.shape == b.shape
print(same_size)



(2, 3, 5)
(5, 2, 3)
False



### 8. Are you able to add a and b? Why or why not?


In [ ]:
### [your code here]
can_add=a.shape==b.shape
print(can_add)
# no i am not able to add a and b because they have different sizes and it should be the same size of column in first matrix with the first row in the second matrix



False




### 9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".


In [39]:
### [your code here]
c = b.transpose(1,2,0)
print(c)
c.shape


[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


(2, 3, 5)


### 10. Try to add a and c. Now it should work. Assign the sum to variable "d". But why does it work now?


In [36]:
### [your code here]
d=a+c



### 11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.


In [ ]:
### [your code here]
print(a)
print(d)
#



[[[5 0 5 3 4]
  [7 2 8 0 7]
  [6 0 4 5 3]]

 [[9 5 4 0 9]
  [0 2 6 3 2]
  [5 3 5 2 0]]]
[[[ 6.  1.  6.  4.  5.]
  [ 8.  3.  9.  1.  8.]
  [ 7.  1.  5.  6.  4.]]

 [[10.  6.  5.  1. 10.]
  [ 1.  3.  7.  4.  3.]
  [ 6.  4.  6.  3.  1.]]]



### 12. Multiply a and c. Assign the result to e.


In [42]:
### [your code here]
e=a*c
print(e)
e.shape


[[[5. 0. 5. 3. 4.]
  [7. 2. 8. 0. 7.]
  [6. 0. 4. 5. 3.]]

 [[9. 5. 4. 0. 9.]
  [0. 2. 6. 3. 2.]
  [5. 3. 5. 2. 0.]]]


(2, 3, 5)



### 13. Does e equal to a? Why or why not?


In [ ]:
### [your code here]
eq=a.shape==e.shape
print(eq)
print(e.shape)
print(a.shape)
# yes e equals to a they both have the same shape and size



True
(2, 3, 5)
(2, 3, 5)




### 14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"


In [47]:
### [your code here]
d_max=np.max(d)
d_min=np.min(d)
d_mean=np.mean(d)




### 15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.


In [48]:
### [your code here]
f=np.empty((2,3,5))





### 16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.



In [75]:
### [your code here]
f = np.empty(d.shape)

for i in range(d.shape[0]):  
    for j in range(d.shape[1]):  
        for k in range(d.shape[2]):  
            if d_min < d[i, j, k] < d_mean:
                f[i, j, k] = 25
            elif d_mean < d[i, j, k] < d_max:
                f[i, j, k] = 75
            elif d[i,j,k]== d_max:
                f[i, j, k] = 100
            else:
                  f[i, j, k] = 0  












### 17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])



In [76]:
### [your code here]
print(d)
print(f)


[[[ 6.  1.  6.  4.  5.]
  [ 8.  3.  9.  1.  8.]
  [ 7.  1.  5.  6.  4.]]

 [[10.  6.  5.  1. 10.]
  [ 1.  3.  7.  4.  3.]
  [ 6.  4.  6.  3.  1.]]]
[[[ 75.   0.  75.  25.  75.]
  [ 75.  25.  75.   0.  75.]
  [ 75.   0.  75.  75.  25.]]

 [[100.  75.  75.   0. 100.]
  [  0.  25.  75.  25.  25.]
  [ 75.  25.  75.  25.   0.]]]


### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.

In [36]:
### [your code here]